# -*- coding: utf-8 -*-
"""Regenerate web/js/data.js from the Tkinter program's embedded base data.

The desktop program stores its base data (Input items, Output activities and the
산출기준 Unit M/H tables) as one JSON blob inside
FEED_MH_Calculator_V0_4_OPExcelGrid.py.  The web app ships the same data as
web/js/data.js, with the Korean display strings translated to English using
tools/ko_en.json.

Deliberately NOT translated, because they are calculation keys rather than
display text:

  * the 상 / 중 / 하 / SPI keys of every std entry's ``int`` / ``ext`` maps,
  * the dictionary keys of the std tables,
  * the stored ``value`` of computed difficulty inputs,

Keeping them in Korean means the calculation stays byte-identical to the Python
model and an exported state file can still be read by the desktop program.  The
web UI translates them for display (see DIFF_LABEL in web/js/model.js).

    python3 tools/gen_web_data.py
"""
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'FEED_MH_Calculator_V0_4_OPExcelGrid.py'
DICT = Path(__file__).resolve().parent / 'ko_en.json'
DST = ROOT / 'web' / 'js' / 'data.js'

HANGUL = re.compile(r'[가-힣]')

# Fields holding display text, per record type.
INPUT_FIELDS = ('section', 'major', 'middle', 'detail', 'note', 'unit')
STD_FIELDS = ('activity', 'unit', 'guide')


def main():
    lines = SRC.read_text(encoding='utf-8').split('\n')

    data_line = next(l for l in lines if l.startswith('DATA=json.loads('))
    data = json.loads(ast.literal_eval(data_line[len('DATA=json.loads('):-1]))

    logo_line = next(l for l in lines if l.startswith('HYUNDAI_LOGO_B64='))
    logo = ast.literal_eval(logo_line[len('HYUNDAI_LOGO_B64='):])

    table = json.loads(DICT.read_text(encoding='utf-8'))
    missing = []

    def tr(value):
        """Translate one display string, remembering anything not in the dictionary."""
        if not isinstance(value, str) or not HANGUL.search(value):
            return value
        if value in table:
            return table[value]
        missing.append(value)
        return value

    def tr_fields(record, fields):
        for f in fields:
            if f in record:
                record[f] = tr(record[f])

    for item in data['inputs']:
        tr_fields(item, INPUT_FIELDS)
        for opt in item.get('options', []):
            opt['text'] = tr(opt.get('text', ''))

    for out in data['outputs']:
        tr_fields(out, ('activity', 'unit'))
        if isinstance(out.get('std'), dict):
            tr_fields(out['std'], STD_FIELDS)

    for part in ('ci', 'tel'):
        for entry in data['std'][part].values():
            tr_fields(entry, STD_FIELDS)

    if missing:
        print('경고 / WARNING: %d string(s) missing from %s:' % (len(missing), DICT.name),
              file=sys.stderr)
        for s in dict.fromkeys(missing):
            print('  ' + json.dumps(s, ensure_ascii=False), file=sys.stderr)

    out = [
        '/* Auto-generated by tools/gen_web_data.py - do not edit by hand. */',
        '/* Base data: Input items, Output activities and the calculation-standard',
        '   (산출기준) Unit M/H tables, translated via tools/ko_en.json.',
        '   The 상/중/하/SPI difficulty keys are intentionally left untranslated:',
        '   they are lookup keys shared with the desktop program. */',
        'var DATA = ' + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';',
        '',
        "var HYUNDAI_LOGO_B64 = '" + logo + "';",
        '',
    ]
    DST.write_text('\n'.join(out), encoding='utf-8')
    print('%s written (inputs %d / outputs %d / std ci %d, tel %d)' % (
        DST, len(data['inputs']), len(data['outputs']),
        len(data['std']['ci']), len(data['std']['tel'])))
    return 1 if missing else 0


if __name__ == '__main__':
    raise SystemExit(main())
