# -*- coding: utf-8 -*-
"""Rebuild the data block inside the single-file web app.

FEED_MH_Calculator.html is self-contained: styles, model, report generator and
base data all live in that one file. This script refreshes only the generated
data block - the part between

    <!-- ===== BEGIN GENERATED DATA ... ===== -->
    <!-- ===== END GENERATED DATA ===== -->

- from the base data embedded in FEED_MH_Calculator_V0_4_OPExcelGrid.py (Input
items, Output activities, the calculation-standard Unit M/H tables and the
logo), translating the Korean display strings via tools/ko_en.json.

Deliberately NOT translated, because they are calculation keys rather than
display text:

  * the 상 / 중 / 하 / SPI keys of every std entry's ``int`` / ``ext`` maps,
  * the dictionary keys of the std tables,
  * the stored ``value`` of computed difficulty inputs.

Keeping them in Korean means the calculation stays byte-identical to the Python
model and an exported state file can still be read by the desktop program. The
web UI translates them for display (see DIFF_LABEL in the MH model block).

    python3 tools/gen_web_data.py
"""
import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / 'FEED_MH_Calculator_V0_4_OPExcelGrid.py'
DICT = Path(__file__).resolve().parent / 'ko_en.json'
APP = ROOT / 'FEED_MH_Calculator.html'

BEGIN = '<!-- ===== BEGIN GENERATED DATA'
END = '<!-- ===== END GENERATED DATA ===== -->'

HANGUL = re.compile(r'[가-힣]')

# Fields holding display text, per record type.
INPUT_FIELDS = ('section', 'major', 'middle', 'detail', 'note', 'unit')
STD_FIELDS = ('activity', 'unit', 'guide')


def build_data():
    """Read the base data out of the Python program and translate it."""
    lines = SRC.read_text(encoding='utf-8').split('\n')

    data_line = next(l for l in lines if l.startswith('DATA=json.loads('))
    data = json.loads(ast.literal_eval(data_line[len('DATA=json.loads('):-1]))

    logo_line = next(l for l in lines if l.startswith('HYUNDAI_LOGO_B64='))
    logo = ast.literal_eval(logo_line[len('HYUNDAI_LOGO_B64='):])

    table = json.loads(DICT.read_text(encoding='utf-8'))
    missing = []

    def tr(value):
        """Translate one display string, remembering anything not in the dictionary."""
        if not isinstance(value, str) or not HANGUL.search(value):
            return value
        if value in table:
            return table[value]
        missing.append(value)
        return value

    def tr_fields(record, fields):
        for f in fields:
            if f in record:
                record[f] = tr(record[f])

    for item in data['inputs']:
        tr_fields(item, INPUT_FIELDS)
        for opt in item.get('options', []):
            opt['text'] = tr(opt.get('text', ''))

    for out in data['outputs']:
        tr_fields(out, ('activity', 'unit'))
        if isinstance(out.get('std'), dict):
            tr_fields(out['std'], STD_FIELDS)

    for part in ('ci', 'tel'):
        for entry in data['std'][part].values():
            tr_fields(entry, STD_FIELDS)

    return data, logo, missing


def render_block(data, logo):
    payload = json.dumps(data, ensure_ascii=False, separators=(',', ':'))
    # `</script` inside a string literal would end the inline script element.
    payload = payload.replace('</script', '<\\/script')
    return '\n'.join([
        '<script id="app-data">',
        '/* Auto-generated by tools/gen_web_data.py - do not edit by hand. */',
        '/* Base data: Input items, Output activities and the calculation-standard',
        '   (산출기준) Unit M/H tables, translated via tools/ko_en.json.',
        '   The 상/중/하/SPI difficulty keys are intentionally left untranslated:',
        '   they are lookup keys shared with the desktop program. */',
        'var DATA = ' + payload + ';',
        '',
        "var HYUNDAI_LOGO_B64 = '" + logo + "';",
        '</script>',
    ])


def main():
    data, logo, missing = build_data()

    html = APP.read_text(encoding='utf-8')
    try:
        start = html.index(BEGIN)
        end = html.index(END, start) + len(END)
    except ValueError:
        print('ERROR: generated-data markers not found in %s' % APP.name, file=sys.stderr)
        return 2
    head_marker_end = html.index('-->', start) + len('-->')

    new = (html[:head_marker_end] + '\n' + render_block(data, logo) + '\n' + html[end - len(END):])
    APP.write_text(new, encoding='utf-8')

    if missing:
        print('WARNING: %d string(s) missing from %s:' % (len(missing), DICT.name),
              file=sys.stderr)
        for s in dict.fromkeys(missing):
            print('  ' + json.dumps(s, ensure_ascii=False), file=sys.stderr)

    print('%s data block rebuilt (inputs %d / outputs %d / std ci %d, tel %d)' % (
        APP.name, len(data['inputs']), len(data['outputs']),
        len(data['std']['ci']), len(data['std']['tel'])))
    return 1 if missing else 0


if __name__ == '__main__':
    raise SystemExit(main())
